/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VariantsRouteImport } from './routes/variants'
import { Route as UploadsRouteImport } from './routes/uploads'
import { Route as TeamRouteImport } from './routes/team'
import { Route as StructuralBiologyRouteImport } from './routes/structural-biology'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PolicyRouteImport } from './routes/policy'
import { Route as PhylogenyRouteImport } from './routes/phylogeny'
import { Route as PendingRouteImport } from './routes/pending'
import { Route as PathogensRouteImport } from './routes/pathogens'
import { Route as PartnershipsRouteImport } from './routes/partnerships'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as NewsRouteImport } from './routes/news'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LineagesRouteImport } from './routes/lineages'
import { Route as LabNetworkRouteImport } from './routes/lab-network'
import { Route as IngestRouteImport } from './routes/ingest'
import { Route as GenomicsRouteImport } from './routes/genomics'
import { Route as ForecastingRouteImport } from './routes/forecasting'
import { Route as ForecastCompareRouteImport } from './routes/forecast-compare'
import { Route as EpidemiologyRouteImport } from './routes/epidemiology'
import { Route as EnvironmentRouteImport } from './routes/environment'
import { Route as EmergencyRouteImport } from './routes/emergency'
import { Route as CountriesRouteImport } from './routes/countries'
import { Route as BiosecurityRouteImport } from './routes/biosecurity'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as ApiDocsRouteImport } from './routes/api-docs'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AcademyRouteImport } from './routes/academy'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as IntelSignalRouteImport } from './routes/intel.$signal'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSecurityRouteImport } from './routes/admin.security'
import { Route as AdminRolesRouteImport } from './routes/admin.roles'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'

const VariantsRoute = VariantsRouteImport.update({
  id: '/variants',
  path: '/variants',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadsRoute = UploadsRouteImport.update({
  id: '/uploads',
  path: '/uploads',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const StructuralBiologyRoute = StructuralBiologyRouteImport.update({
  id: '/structural-biology',
  path: '/structural-biology',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PolicyRoute = PolicyRouteImport.update({
  id: '/policy',
  path: '/policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PhylogenyRoute = PhylogenyRouteImport.update({
  id: '/phylogeny',
  path: '/phylogeny',
  getParentRoute: () => rootRouteImport,
} as any)
const PendingRoute = PendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => rootRouteImport,
} as any)
const PathogensRoute = PathogensRouteImport.update({
  id: '/pathogens',
  path: '/pathogens',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnershipsRoute = PartnershipsRouteImport.update({
  id: '/partnerships',
  path: '/partnerships',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LineagesRoute = LineagesRouteImport.update({
  id: '/lineages',
  path: '/lineages',
  getParentRoute: () => rootRouteImport,
} as any)
const LabNetworkRoute = LabNetworkRouteImport.update({
  id: '/lab-network',
  path: '/lab-network',
  getParentRoute: () => rootRouteImport,
} as any)
const IngestRoute = IngestRouteImport.update({
  id: '/ingest',
  path: '/ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const GenomicsRoute = GenomicsRouteImport.update({
  id: '/genomics',
  path: '/genomics',
  getParentRoute: () => rootRouteImport,
} as any)
const ForecastingRoute = ForecastingRouteImport.update({
  id: '/forecasting',
  path: '/forecasting',
  getParentRoute: () => rootRouteImport,
} as any)
const ForecastCompareRoute = ForecastCompareRouteImport.update({
  id: '/forecast-compare',
  path: '/forecast-compare',
  getParentRoute: () => rootRouteImport,
} as any)
const EpidemiologyRoute = EpidemiologyRouteImport.update({
  id: '/epidemiology',
  path: '/epidemiology',
  getParentRoute: () => rootRouteImport,
} as any)
const EnvironmentRoute = EnvironmentRouteImport.update({
  id: '/environment',
  path: '/environment',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergencyRoute = EmergencyRouteImport.update({
  id: '/emergency',
  path: '/emergency',
  getParentRoute: () => rootRouteImport,
} as any)
const CountriesRoute = CountriesRouteImport.update({
  id: '/countries',
  path: '/countries',
  getParentRoute: () => rootRouteImport,
} as any)
const BiosecurityRoute = BiosecurityRouteImport.update({
  id: '/biosecurity',
  path: '/biosecurity',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocsRoute = ApiDocsRouteImport.update({
  id: '/api-docs',
  path: '/api-docs',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyRoute = AcademyRouteImport.update({
  id: '/academy',
  path: '/academy',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const IntelSignalRoute = IntelSignalRouteImport.update({
  id: '/intel/$signal',
  path: '/intel/$signal',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSecurityRoute = AdminSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academy': typeof AcademyRoute
  '/admin': typeof AdminRouteWithChildren
  '/alerts': typeof AlertsRoute
  '/api-docs': typeof ApiDocsRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/biosecurity': typeof BiosecurityRoute
  '/countries': typeof CountriesRoute
  '/emergency': typeof EmergencyRoute
  '/environment': typeof EnvironmentRoute
  '/epidemiology': typeof EpidemiologyRoute
  '/forecast-compare': typeof ForecastCompareRoute
  '/forecasting': typeof ForecastingRoute
  '/genomics': typeof GenomicsRoute
  '/ingest': typeof IngestRoute
  '/lab-network': typeof LabNetworkRoute
  '/lineages': typeof LineagesRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/methodology': typeof MethodologyRoute
  '/news': typeof NewsRoute
  '/notifications': typeof NotificationsRoute
  '/partnerships': typeof PartnershipsRoute
  '/pathogens': typeof PathogensRoute
  '/pending': typeof PendingRoute
  '/phylogeny': typeof PhylogenyRoute
  '/policy': typeof PolicyRoute
  '/reports': typeof ReportsRoute
  '/search': typeof SearchRoute
  '/structural-biology': typeof StructuralBiologyRoute
  '/team': typeof TeamRoute
  '/uploads': typeof UploadsRoute
  '/variants': typeof VariantsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/chat': typeof ApiChatRoute
  '/intel/$signal': typeof IntelSignalRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academy': typeof AcademyRoute
  '/alerts': typeof AlertsRoute
  '/api-docs': typeof ApiDocsRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/biosecurity': typeof BiosecurityRoute
  '/countries': typeof CountriesRoute
  '/emergency': typeof EmergencyRoute
  '/environment': typeof EnvironmentRoute
  '/epidemiology': typeof EpidemiologyRoute
  '/forecast-compare': typeof ForecastCompareRoute
  '/forecasting': typeof ForecastingRoute
  '/genomics': typeof GenomicsRoute
  '/ingest': typeof IngestRoute
  '/lab-network': typeof LabNetworkRoute
  '/lineages': typeof LineagesRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/methodology': typeof MethodologyRoute
  '/news': typeof NewsRoute
  '/notifications': typeof NotificationsRoute
  '/partnerships': typeof PartnershipsRoute
  '/pathogens': typeof PathogensRoute
  '/pending': typeof PendingRoute
  '/phylogeny': typeof PhylogenyRoute
  '/policy': typeof PolicyRoute
  '/reports': typeof ReportsRoute
  '/search': typeof SearchRoute
  '/structural-biology': typeof StructuralBiologyRoute
  '/team': typeof TeamRoute
  '/uploads': typeof UploadsRoute
  '/variants': typeof VariantsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/chat': typeof ApiChatRoute
  '/intel/$signal': typeof IntelSignalRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academy': typeof AcademyRoute
  '/admin': typeof AdminRouteWithChildren
  '/alerts': typeof AlertsRoute
  '/api-docs': typeof ApiDocsRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/biosecurity': typeof BiosecurityRoute
  '/countries': typeof CountriesRoute
  '/emergency': typeof EmergencyRoute
  '/environment': typeof EnvironmentRoute
  '/epidemiology': typeof EpidemiologyRoute
  '/forecast-compare': typeof ForecastCompareRoute
  '/forecasting': typeof ForecastingRoute
  '/genomics': typeof GenomicsRoute
  '/ingest': typeof IngestRoute
  '/lab-network': typeof LabNetworkRoute
  '/lineages': typeof LineagesRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/methodology': typeof MethodologyRoute
  '/news': typeof NewsRoute
  '/notifications': typeof NotificationsRoute
  '/partnerships': typeof PartnershipsRoute
  '/pathogens': typeof PathogensRoute
  '/pending': typeof PendingRoute
  '/phylogeny': typeof PhylogenyRoute
  '/policy': typeof PolicyRoute
  '/reports': typeof ReportsRoute
  '/search': typeof SearchRoute
  '/structural-biology': typeof StructuralBiologyRoute
  '/team': typeof TeamRoute
  '/uploads': typeof UploadsRoute
  '/variants': typeof VariantsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/chat': typeof ApiChatRoute
  '/intel/$signal': typeof IntelSignalRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/academy'
    | '/admin'
    | '/alerts'
    | '/api-docs'
    | '/assistant'
    | '/auth'
    | '/biosecurity'
    | '/countries'
    | '/emergency'
    | '/environment'
    | '/epidemiology'
    | '/forecast-compare'
    | '/forecasting'
    | '/genomics'
    | '/ingest'
    | '/lab-network'
    | '/lineages'
    | '/login'
    | '/marketplace'
    | '/methodology'
    | '/news'
    | '/notifications'
    | '/partnerships'
    | '/pathogens'
    | '/pending'
    | '/phylogeny'
    | '/policy'
    | '/reports'
    | '/search'
    | '/structural-biology'
    | '/team'
    | '/uploads'
    | '/variants'
    | '/admin/audit'
    | '/admin/dashboard'
    | '/admin/roles'
    | '/admin/security'
    | '/admin/users'
    | '/api/chat'
    | '/intel/$signal'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/academy'
    | '/alerts'
    | '/api-docs'
    | '/assistant'
    | '/auth'
    | '/biosecurity'
    | '/countries'
    | '/emergency'
    | '/environment'
    | '/epidemiology'
    | '/forecast-compare'
    | '/forecasting'
    | '/genomics'
    | '/ingest'
    | '/lab-network'
    | '/lineages'
    | '/login'
    | '/marketplace'
    | '/methodology'
    | '/news'
    | '/notifications'
    | '/partnerships'
    | '/pathogens'
    | '/pending'
    | '/phylogeny'
    | '/policy'
    | '/reports'
    | '/search'
    | '/structural-biology'
    | '/team'
    | '/uploads'
    | '/variants'
    | '/admin/audit'
    | '/admin/dashboard'
    | '/admin/roles'
    | '/admin/security'
    | '/admin/users'
    | '/api/chat'
    | '/intel/$signal'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/academy'
    | '/admin'
    | '/alerts'
    | '/api-docs'
    | '/assistant'
    | '/auth'
    | '/biosecurity'
    | '/countries'
    | '/emergency'
    | '/environment'
    | '/epidemiology'
    | '/forecast-compare'
    | '/forecasting'
    | '/genomics'
    | '/ingest'
    | '/lab-network'
    | '/lineages'
    | '/login'
    | '/marketplace'
    | '/methodology'
    | '/news'
    | '/notifications'
    | '/partnerships'
    | '/pathogens'
    | '/pending'
    | '/phylogeny'
    | '/policy'
    | '/reports'
    | '/search'
    | '/structural-biology'
    | '/team'
    | '/uploads'
    | '/variants'
    | '/admin/audit'
    | '/admin/dashboard'
    | '/admin/roles'
    | '/admin/security'
    | '/admin/users'
    | '/api/chat'
    | '/intel/$signal'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AcademyRoute: typeof AcademyRoute
  AdminRoute: typeof AdminRouteWithChildren
  AlertsRoute: typeof AlertsRoute
  ApiDocsRoute: typeof ApiDocsRoute
  AssistantRoute: typeof AssistantRoute
  AuthRoute: typeof AuthRoute
  BiosecurityRoute: typeof BiosecurityRoute
  CountriesRoute: typeof CountriesRoute
  EmergencyRoute: typeof EmergencyRoute
  EnvironmentRoute: typeof EnvironmentRoute
  EpidemiologyRoute: typeof EpidemiologyRoute
  ForecastCompareRoute: typeof ForecastCompareRoute
  ForecastingRoute: typeof ForecastingRoute
  GenomicsRoute: typeof GenomicsRoute
  IngestRoute: typeof IngestRoute
  LabNetworkRoute: typeof LabNetworkRoute
  LineagesRoute: typeof LineagesRoute
  LoginRoute: typeof LoginRoute
  MarketplaceRoute: typeof MarketplaceRoute
  MethodologyRoute: typeof MethodologyRoute
  NewsRoute: typeof NewsRoute
  NotificationsRoute: typeof NotificationsRoute
  PartnershipsRoute: typeof PartnershipsRoute
  PathogensRoute: typeof PathogensRoute
  PendingRoute: typeof PendingRoute
  PhylogenyRoute: typeof PhylogenyRoute
  PolicyRoute: typeof PolicyRoute
  ReportsRoute: typeof ReportsRoute
  SearchRoute: typeof SearchRoute
  StructuralBiologyRoute: typeof StructuralBiologyRoute
  TeamRoute: typeof TeamRoute
  UploadsRoute: typeof UploadsRoute
  VariantsRoute: typeof VariantsRoute
  ApiChatRoute: typeof ApiChatRoute
  IntelSignalRoute: typeof IntelSignalRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/variants': {
      id: '/variants'
      path: '/variants'
      fullPath: '/variants'
      preLoaderRoute: typeof VariantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uploads': {
      id: '/uploads'
      path: '/uploads'
      fullPath: '/uploads'
      preLoaderRoute: typeof UploadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/structural-biology': {
      id: '/structural-biology'
      path: '/structural-biology'
      fullPath: '/structural-biology'
      preLoaderRoute: typeof StructuralBiologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policy': {
      id: '/policy'
      path: '/policy'
      fullPath: '/policy'
      preLoaderRoute: typeof PolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phylogeny': {
      id: '/phylogeny'
      path: '/phylogeny'
      fullPath: '/phylogeny'
      preLoaderRoute: typeof PhylogenyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pending': {
      id: '/pending'
      path: '/pending'
      fullPath: '/pending'
      preLoaderRoute: typeof PendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pathogens': {
      id: '/pathogens'
      path: '/pathogens'
      fullPath: '/pathogens'
      preLoaderRoute: typeof PathogensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partnerships': {
      id: '/partnerships'
      path: '/partnerships'
      fullPath: '/partnerships'
      preLoaderRoute: typeof PartnershipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lineages': {
      id: '/lineages'
      path: '/lineages'
      fullPath: '/lineages'
      preLoaderRoute: typeof LineagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab-network': {
      id: '/lab-network'
      path: '/lab-network'
      fullPath: '/lab-network'
      preLoaderRoute: typeof LabNetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingest': {
      id: '/ingest'
      path: '/ingest'
      fullPath: '/ingest'
      preLoaderRoute: typeof IngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/genomics': {
      id: '/genomics'
      path: '/genomics'
      fullPath: '/genomics'
      preLoaderRoute: typeof GenomicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forecasting': {
      id: '/forecasting'
      path: '/forecasting'
      fullPath: '/forecasting'
      preLoaderRoute: typeof ForecastingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forecast-compare': {
      id: '/forecast-compare'
      path: '/forecast-compare'
      fullPath: '/forecast-compare'
      preLoaderRoute: typeof ForecastCompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/epidemiology': {
      id: '/epidemiology'
      path: '/epidemiology'
      fullPath: '/epidemiology'
      preLoaderRoute: typeof EpidemiologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/environment': {
      id: '/environment'
      path: '/environment'
      fullPath: '/environment'
      preLoaderRoute: typeof EnvironmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emergency': {
      id: '/emergency'
      path: '/emergency'
      fullPath: '/emergency'
      preLoaderRoute: typeof EmergencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/countries': {
      id: '/countries'
      path: '/countries'
      fullPath: '/countries'
      preLoaderRoute: typeof CountriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biosecurity': {
      id: '/biosecurity'
      path: '/biosecurity'
      fullPath: '/biosecurity'
      preLoaderRoute: typeof BiosecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-docs': {
      id: '/api-docs'
      path: '/api-docs'
      fullPath: '/api-docs'
      preLoaderRoute: typeof ApiDocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy': {
      id: '/academy'
      path: '/academy'
      fullPath: '/academy'
      preLoaderRoute: typeof AcademyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/intel/$signal': {
      id: '/intel/$signal'
      path: '/intel/$signal'
      fullPath: '/intel/$signal'
      preLoaderRoute: typeof IntelSignalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/security': {
      id: '/admin/security'
      path: '/security'
      fullPath: '/admin/security'
      preLoaderRoute: typeof AdminSecurityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAuditRoute: typeof AdminAuditRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminSecurityRoute: typeof AdminSecurityRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditRoute: AdminAuditRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminSecurityRoute: AdminSecurityRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AcademyRoute: AcademyRoute,
  AdminRoute: AdminRouteWithChildren,
  AlertsRoute: AlertsRoute,
  ApiDocsRoute: ApiDocsRoute,
  AssistantRoute: AssistantRoute,
  AuthRoute: AuthRoute,
  BiosecurityRoute: BiosecurityRoute,
  CountriesRoute: CountriesRoute,
  EmergencyRoute: EmergencyRoute,
  EnvironmentRoute: EnvironmentRoute,
  EpidemiologyRoute: EpidemiologyRoute,
  ForecastCompareRoute: ForecastCompareRoute,
  ForecastingRoute: ForecastingRoute,
  GenomicsRoute: GenomicsRoute,
  IngestRoute: IngestRoute,
  LabNetworkRoute: LabNetworkRoute,
  LineagesRoute: LineagesRoute,
  LoginRoute: LoginRoute,
  MarketplaceRoute: MarketplaceRoute,
  MethodologyRoute: MethodologyRoute,
  NewsRoute: NewsRoute,
  NotificationsRoute: NotificationsRoute,
  PartnershipsRoute: PartnershipsRoute,
  PathogensRoute: PathogensRoute,
  PendingRoute: PendingRoute,
  PhylogenyRoute: PhylogenyRoute,
  PolicyRoute: PolicyRoute,
  ReportsRoute: ReportsRoute,
  SearchRoute: SearchRoute,
  StructuralBiologyRoute: StructuralBiologyRoute,
  TeamRoute: TeamRoute,
  UploadsRoute: UploadsRoute,
  VariantsRoute: VariantsRoute,
  ApiChatRoute: ApiChatRoute,
  IntelSignalRoute: IntelSignalRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
